import = [
    "~/.config/alacritty/themes/themes/citylights.toml"
]

[shell]
program = "tmux"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "block"
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.glyph_offset]
y = 0

[font.normal]
family = "Fira Code Nerd Font"

[font.offset]
y = 0

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_title = false
title = "Alacritty"
opacity = 0.9
startup_mode = "windowed"

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 5
y = 5
